version: "3.8"
services:

    php:
        build: .
        container_name: laravel-typeahead-php
        tty: true
        volumes:
            - ./php:/var/www/html:rw
        networks:
            - app-network
    
    nginx:
        image: nginx:alpine
        container_name: laravel-typeahead-nginx
        tty: true
        volumes:
            - ./php:/var/www/html:rw
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge