version: "3.8"
services:

    php:
        build: .
        container_name: laravel-typeahead-php
        tty: true
        volumes:
            - ./php:/var/www/html:rw
        networks:
            - app-network
    
    nginx:
        image: nginx:alpine
        container_name: laravel-typeahead-nginx
        tty: true
        volumes:
            - ./php:/var/www/html:rw
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
    
    mongodb:
        container_name: laravel-typeahead-mongodb
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=piu_anyhowstep
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        networks:
            - app-network
    
    mongo-express:
        image: mongo-express
        container_name: laravel-typeahead-mongo-express
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=laravel-typeahead-mongodb
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
        depends_on:
            - mongodb
        ports:
            - "8081:8081"
        restart: on-failure
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb: